### ISSUE TITLE
About Replication Baseline

### ISSUE THREAD

**Issue by cyttong** [JieZheng-ShanghaiTech/PiLSL#1]
Hello, do you have any code for the baseline? If so, would you please upload it as soon as possible？Thank you very much.

**Comment by jacksliu** [comment]
Hi, which specific baseline you're referring to?

**Comment by jacksliu** [comment]
> Hello, do you have any code for the baseline? If so, would you please upload it as soon as possible？Thank you very much.

Hi, which specific baseline you're referring to?

**Comment by cyttong** [comment]
Thank you very much for your reply, I want to use the new method of dividing data C1, C2, C3 to run the baseline, I don't know how you divide the baseline data? For example, baseline GCATSL, the training data is five test_arr_.txt, can you tell me how to use the evaluation scheme of the new computational prediction method to run the baseline? I don't know if I made it clear, but thank you very much.



At 2023-03-29 14:05:44, "Xin Liu" ***@***.***> wrote:

Hello, do you have any code for the baseline? If so, would you please upload it as soon as possible？Thank you very much.

Hi, which specific baseline you're referring to?

**Comment by jacksliu** [comment]
You can refer to “https://github.com/lichenbiostat/GCATSL#inputs”. The one input of GCATSL is a 'adj.txt' which includes the gene pairs and labels.

**Comment by jacksliu** [comment]
> Thank you very much for your reply, I want to use the new method of dividing data C1, C2, C3 to run the baseline, I don't know how you divide the baseline data? For example, baseline GCATSL, the training data is five test_arr_.txt, can you tell me how to use the evaluation scheme of the new computational prediction method to run the baseline? I don't know if I made it clear, but thank you very much. At 2023-03-29 14:05:44, "Xin Liu" ***@***.***> wrote: Hello, do you have any code for the baseline? If so, would you please upload it as soon as possible？Thank you very much. Hi, which specific baseline you're referring to? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

You can refer to “https://github.com/lichenbiostat/GCATSL#inputs”. The one input of GCATSL is a 'adj.txt' which includes the gene pairs and labels.

**Comment by cyttong** [comment]
In PiLSL, how do you divide the C1, C2, and C3 datasets, and is there any code that can be reproduced?

**Comment by cyttong** [comment]
In PiLSL, how do you divide the C1, C2, and C3 datasets, and is there any code that can be reproduced?



At 2023-03-29 17:38:44, "Xin Liu" ***@***.***> wrote:

Thank you very much for your reply, I want to use the new method of dividing data C1, C2, C3 to run the baseline, I don't know how you divide the baseline data? For example, baseline GCATSL, the training data is five test_arr_.txt, can you tell me how to use the evaluation scheme of the new computational prediction method to run the baseline? I don't know if I made it clear, but thank you very much. At 2023-03-29 14:05:44, "Xin Liu" @.> wrote: Hello, do you have any code for the baseline? If so, would you please upload it as soon as possible？Thank you very much. Hi, which specific baseline you're referring to? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.>

You can refer to “https://github.com/lichenbiostat/GCATSL#inputs”. The one input of GCATSL is a 'adj.txt' which includes the gene pairs and labels.

**Comment by cyttong** [comment]
Where can I find the code and data for replicating the baseline  SL2MF?
