### ISSUE TITLE
Visualization of Fig. 5

### ISSUE THREAD

**Issue by mrxgavin** [JieZheng-ShanghaiTech/PiLSL#2]
Hello! I have a question regarding the visualization implementation in the paper for Fig. 5. PiLSL highlights the meaningful edges from the original enclosing graph and forms reasoning paths to understand the SL interaction. The type of interaction and attention score are labeled on each edge.

Could you please guide me on how to find the IDs and corresponding text names? If possible, could you provide the code or some ideas on how to implement this? I have tried for a long time but couldn't succeed. Any help would be greatly appreciated. Thank you in advance!

**Comment by jacksliu** [comment]
Hi, the IDs and names of entities and edges used in PiLSL experiments are the same as those in KG4SL. You can refer to: https://github.com/JieZheng-ShanghaiTech/KG4SL/tree/main/data.
